services:
  snatcharr:
    image: ghcr.io/lordmaa/snatcharr:latest
    container_name: snatcharr
    restart: unless-stopped
    ports:
      - "6060:6060"
    environment:
      - WHISPARR_DB=/whisparr-config/whisparr3.db
      - SNATCHARR_DATA=/data
    volumes:
      - /home/rob/snatcharr/data:/data
      - /portainer/files/appdata/config/whisparrv3:/whisparr-config:ro
      - /mnt/nas/downloads:/mnt/nas/downloads
